import type { SkillDef } from '../skill-store.js';

// Split into sections to stay within write limits, then join
const section1 = [
  '# faui 数据绑定',
  '',
  '## value.path 绑定',
  '',
  '组件通过 `value.path` 实现双向数据绑定。path 使用 JSON Pointer 格式（以 `/` 开头），指向 dataModel 中的字段。',
  '',
  '读取时组件自动从 dataModel 取值；写入时（如 Input 输入）自动回写到对应路径。',
  '',
  '```json',
  '{',
  '  "component": "input",',
  '  "label": "姓名",',
  '  "value": { "path": "/showcase/expr/name" }',
  '}',
  '```',
  '',
  '对应 dataModel 结构：',
  '```json',
  '{',
  '  "dataModel": {',
  '    "showcase": {',
  '      "expr": {',
  '        "name": "张三"',
  '      }',
  '    }',
  '  }',
  '}',
  '```',
  '',
  '注意：path 是 JSON Pointer，层级用 `/` 分隔，不是点号。`/showcase/expr/name` 对应 `dataModel.showcase.expr.name`。',
].join('\n');

const section2 = [
  '## 表达式语法',
  '',
  'faui 使用 `${expr}` 语法在 JSON 中嵌入动态表达式。可用于组件的任何字符串属性（content、className、visible 等）。',
  '',
  '### 三个上下文变量',
  '',
  '- `$root`：整个 dataModel 根对象',
  '- `$current`：Repeater 内当前迭代项',
  '- `$parent`：Repeater 内当前项所属的父数组',
  '',
  '```json',
  '{',
  '  "component": "typography",',
  '  "content": "${$root.showcase.expr.name}"',
  '}',
  '```',
  '',
  '$root 的顶层字段会展开到表达式作用域，可省略 `$root.`：',
  '```json',
  '{ "content": "你好，${showcase.expr.name}！" }',
  '```',
  '',
  '### 纯表达式 vs 混合文本',
  '',
  '- 纯表达式 `"${count > 0}"` → 返回原始类型（boolean / number / object）',
  '- 混合文本 `"总价: ${price * quantity} 元"` → 返回拼接字符串',
  '',
  '### 内置工具函数',
  '',
  '- `upper(s)`：转大写',
  '- `lower(s)`：转小写',
  '- `isEmpty(v)`：判断 null / undefined / 空字符串 / 空数组',
  '- `sum(arr)`：数组求和',
].join('\n');

const section3 = [
  '## 表达式安全沙箱',
  '',
  '### 可用全局对象',
  'Math, JSON, Object, String, Number, Array, Date, Boolean, parseInt, parseFloat, isNaN, isFinite',
  '',
  '### 不可用（被屏蔽）',
  'window, document, globalThis, self, global, process, eval, Function, setTimeout, setInterval, setImmediate, fetch, XMLHttpRequest, importScripts, require, module, exports',
  '',
  '### 被拦截的属性访问',
  'constructor, __proto__, prototype, __defineGetter__, __defineSetter__',
  '',
  '表达式中出现这些关键词会被直接拦截并返回原始字符串。',
].join('\n');

const section4 = [
  '## Repeater 数据迭代',
  '',
  'Repeater 组件绑定一个数组，为每个元素渲染 children 模板。',
  '',
  '```json',
  '{',
  '  "component": "repeater",',
  '  "data": { "path": "/showcase/list/items" },',
  '  "children": [',
  '    {',
  '      "component": "box",',
  '      "content": "${$current.text}",',
  '      "children": [',
  '        {',
  '          "component": "checkbox",',
  '          "value": { "path": "./done" }',
  '        }',
  '      ]',
  '    }',
  '  ]',
  '}',
  '```',
  '',
  '### 相对路径',
  '',
  'Repeater 内的组件可用 `./` 开头的相对路径，相对于当前迭代项的 scope path：',
  '```json',
  '{ "value": { "path": "./done" } }',
  '```',
  '等价于 `/showcase/list/items/{index}/done`，但不需要知道具体索引。',
  '',
  '### Repeater 内的表达式上下文',
  '',
  '- `$current`：当前迭代项对象，如 `{ "id": 1, "text": "买菜", "done": false }`',
  '- `$parent`：当前项所属的父数组',
  '- `$root`：整个 dataModel',
].join('\n');

const section5 = [
  '## Repeater 删除（重要陷阱）',
  '',
  '删除 Repeater 中的项时，必须用字段值比较，绝不能用引用比较。',
  '',
  '错误写法（引用比较，永远不生效）：',
  '```json',
  '{',
  '  "action": "update_data",',
  '  "path": "/items",',
  '  "value": "${$parent.filter(item => item !== $current)}"',
  '}',
  '```',
  '',
  '正确写法（字段值比较）：',
  '```json',
  '{',
  '  "action": "update_data",',
  '  "path": "/items",',
  '  "value": "${$root.items.filter(x => x.id !== $current.id)}"',
  '}',
  '```',
  '',
  '原因：faui 的 data store 更新时 setByPath 会浅拷贝路径上的对象，导致 $current 与数组中的元素引用不再相等。必须用唯一字段（id、name 等）的值来比较。',
].join('\n');

const section6 = [
  '## Action 系统',
  '',
  'faui 内置三种 action：',
  '',
  '### update_data — 写入数据',
  '```json',
  '{',
  '  "action": "update_data",',
  '  "path": "/counter",',
  '  "value": "${$root.counter + 1}"',
  '}',
  '```',
  'path 指定写入目标，value 支持表达式求值。也支持 `{ "$eval": "expr" }` 旧写法。',
  '',
  '### message — 消息提示',
  '```json',
  '{',
  '  "action": "message",',
  '  "content": "操作成功",',
  '  "type": "success"',
  '}',
  '```',
  '',
  '### notification — 通知',
  '```json',
  '{',
  '  "action": "notification",',
  '  "message": "新消息",',
  '  "description": "你有一条新通知"',
  '}',
  '```',
].join('\n');

const section7 = [
  '## on_change 陷阱（重要）',
  '',
  'Input / Select / Radio 等组件在触发 on_change 时，会用组件的原始值覆盖 action 的 value 字段。',
  '',
  '错误写法：',
  '```json',
  '{',
  '  "component": "select",',
  '  "value": { "path": "/product" },',
  '  "on_change": {',
  '    "action": "update_data",',
  '    "path": "/price",',
  '    "value": "${({\'a\': 100, \'b\': 200})[$root.product]}"',
  '  }',
  '}',
  '```',
  '现象：price 被设为 Select 的原始选中值（如 "a"），而不是表达式结果。',
  '',
  '原因：组件内部执行 `{ ...config.on_change, value: newValue }`，自定义 value 被覆盖。',
  '',
  '正确做法：不通过 on_change 存派生值，在需要的地方用表达式直接计算：',
  '```json',
  '{',
  '  "component": "typography",',
  '  "content": "${({\'a\': 100, \'b\': 200})[$root.product] || \'—\'}"',
  '}',
  '```',
].join('\n');

const section8 = [
  '## Action 链',
  '',
  '### on_tap 数组 — 顺序执行',
  '',
  'on_tap 接受 action 数组，按顺序执行：',
  '```json',
  '{',
  '  "component": "button",',
  '  "content": "提交",',
  '  "on_tap": [',
  '    { "action": "update_data", "path": "/loading", "value": true },',
  '    { "action": "http_proxy", "url": "/api/submit", "method": "POST" },',
  '    { "action": "update_data", "path": "/loading", "value": false },',
  '    { "action": "message", "content": "提交成功", "type": "success" }',
  '  ]',
  '}',
  '```',
  '',
  '### on_success / on_error — 条件链',
  '',
  'http_proxy 等异步 action 支持 on_success 和 on_error 回调：',
  '```json',
  '{',
  '  "action": "http_proxy",',
  '  "url": "/api/data",',
  '  "method": "GET",',
  '  "on_success": [',
  '    { "action": "update_data", "path": "/data", "value": "${$root.__response}" }',
  '  ],',
  '  "on_error": [',
  '    { "action": "notification", "message": "请求失败" }',
  '  ]',
  '}',
  '```',
].join('\n');

const section9 = [
  '## 常见错误',
  '',
  '1. **path 用点号分隔**：错 `"user.name"`，对 `"/user/name"`',
  '2. **Repeater 删除用引用比较**：永远不生效，必须用字段值比较',
  '3. **on_change 里写 value 表达式**：会被组件原始值覆盖，改用表达式直接计算',
  '4. **value 字段传字符串**：`"value": "67+"` 会被当作数据绑定处理（取 .path 为 undefined），应用 `"content"` 或 `"value": { "path": "..." }`',
  '5. **表达式中访问 window/document**：被沙箱屏蔽，返回 undefined',
  '6. **忘记 $root 前缀**：在 Repeater 内 update_data 的 path 表达式中，必须用 `$root.items` 而非 `items`（Repeater 内顶层作用域可能被 $current 遮蔽）',
].join('\n');

export const dataBindingSkill: SkillDef = {
  name: 'data-binding',
  description: '数据绑定规则（value.path、表达式、Repeater、action 链）',
  content: [
    section1, section2, section3, section4,
    section5, section6, section7, section8, section9,
  ].join('\n\n'),
};
